name: nightly-test-hi-there
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
jobs:
  update-mappings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          cd item-shop
          python3 buildmappings.py
      - uses: EndBug/add-and-commit@7 # You can change this to use a specific version
        with:
          add: '.github/*'
          author_name: 48panda48
          author_email: george.48panda@gmail.com
          default_author: 'github_actor'
          message: 'BOT: Updated mappings'
          pull: 'NO-PULL'
          push: true
          signoff: false
      
      - name: Checkout
        run: |
          git config user.email "george.48panda@gmail.com"
          git config user.name "48panda48"

      - name: Build
        run: |
          cd item-shop
          npm install
          npm run build
          cp -a staticbuild/. build/

      - name: "Push to other branch"
        run : |
          git status
          git pull
          git add --all
          git commit -m "Update deployment branch"
          git pull --rebase
          git push origin `git subtree split --prefix item-shop/build main`:deployment --force
