name: nightly-test
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
jobs:
  update-mappings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
            add: '--all'
            author_name: 48panda48
            author_email: georege.48panda@gmail.com
            default_author: github_actor'
            message: 'BOT: Updated mappings'
            pull_strategy: 'NO-PULL
            push: true
            signoff: true
      - run: |
          cd item-shop
          python3 buildmappings.py
      - run: echo done!