name: nightly-test
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
jobs:
  update-mappings:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$GITHUB_ACTION_PATH"
          cd item-shop
          python3 buildmappings.py