name: nightly-test
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
jobs:
  update-mappings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd item-shop
          python3 buildmappings.py
          git add public/mappings.json
          git commit -m "BOT:updated mappings"
          git push