name: nightly-test
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
jobs:
  update-mappings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          cd item-shop
          python3 buildmappings.py

      - name: Build
        run: |
          cd item-shop
          npm install
          npm run build
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '--all'
          author_name: 48panda48
          author_email: george.48panda@gmail.com
          default_author: 'github_actor'
          message: 'BOT: Updated mappings'
          pull_strategy: 'NO-PULL'
          push: true
          signoff: true
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '--all'
          author_name: 48panda48
          author_email: george.48panda@gmail.com
          branch: deployment
          default_author: 'github_actor'
          message: 'BOT: Rebuilt due to new push.'
          pull_strategy: 'NO-PULL'
          push: true
          signoff: true
          cwd: './item-shop/build'